#!/usr/bin/env groovy

pipeline {
    agent none
    stages {
        stage('Build') {
            steps {
                echo "Iniciando o build"
                sh "mvn package -Dmaven.test.skip=true"
            }
        }
        stage('Test') {
            steps {
                echo "Iniciando os testes"
                sh "mvn clean install"
            }
        }
    }
}